version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: nest-api-dev
    volumes:
      - .:/usr/src/app
    restart: always
    command: npm run start:dev
    expose:
      - 3420
    ports:
      - 3420:3420
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public

  postgres:
    image: postgres:14
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - nest-postgres:/var/lib/postgresql/data

  redis:
    container_name: cache
    image: redis
    command: redis-server --requirepass redis123
    expose:
      - 6379
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  rcli:
      image: redis:latest
      links:
        - redis
      command: redis-cli -h redis

volumes:
  redis:
    driver: local
  nest-postgres:
