version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: nest-api-dev
    volumes:
          - .:/usr/src/app
    restart: always
    command: npm run start:dev
    ports:
      - 3000:3000
    depends_on:
      - nest-postgres
    env_file:
      - .env

  nest-postgres:
    image: postgres:14
    container_name: nest-postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - nest-postgres:/var/lib/postgresql/data

volumes:
  nest-postgres:
    name: nest-postgres-db
